# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/mahabharata',
                'doc_host': 'https://pvry.github.io',
                'git_url': 'https://github.com/pvry/mahabharata',
                'lib_path': 'mahabharata'},
  'syms': {'mahabharata.core': {'mahabharata.core.foo': ('core.html#foo', 'mahabharata/core.py')}}}